# This if the main configuration file for Automaton.
#
# Configuration Settings:
# -----------------------
#
#
# A few things to note:
# ---------------------
#   1) You do not need to create the collections before hand.
#   2) If you use a ReplicaSet then set the following => replicaset: no
#      otherwise ONLY THE FIRST HOST will be used
#   3) Puppet Inventory Service MUST be setup on the puppetmaster in order
#      to use facter fact interpolation in ENC data.
#

# Database Configuration
#database_type: 'mongo' or 'yaml' or 'json'
database_type:  'mongo'

# Mongo Configuration
mdb_hosts:      '10.40.30.60:9969,mongohost001b:27017,mongohost001c:27017'
replicaset:     'no'
#username:       ''
#password:       ''
database:       'automaton'
nodecollection: 'enc'
factcollection: 'facts'

# Flat File Configuration
data_path:      '/home/shellfu/opt/nodes'

# Puppet & Facter Configuration
# Inventory Service must be setup on the puppet master in order to use fact interpolation
environment:    'production'
inventoryurl:   'https://10.40.30.163'
inventoryport:  '8140'
enablefacts:    'true'

# Logging Configuration
logpath:        '/home/shellfu/var/logs/automaton.log'
enablelog:      'true'
verbose:        'false'
debug:          'false'

