#
# CONFIG.YML
#
# This if the main configuration file for Automaton.
#
# Configuration Settings:
# -----------------------
# [ Automaton Database Type] :
#  DATABASE_TYPE: this is the "type" of database to use, be it mongo, json or yaml
#    database_type: '[mongo | yaml | json]'
#
#
# [ Mongo Configuration ]:
# If you're using mongodb for fact, and node definition storage, you can configure mongo here.
#
#  MDB_HOSTS: this is either be  a single mongo instance, or a replica set.
#    mdb_hosts: '[ HOST:PORT | HOST01:PORT,HOST02:PORT,HOST03:PORT']
#
#  REPLICA_SET: this can be yes or no. If yes then automaton will connect to the entire replica set listed in MDB_HOSTS
#   otherwise, automaton will connect to only the first host listed in MDB_HOSTS regardless of how many are listed.
##   replicaset: '[ yes | no ]'
#
#  USERNAME: The username for mongo, if you do not use authentication, then leave it commented out.
#    username: '[ USERNAME ]'
#
#  DATABASE: The name of the database to use in mongo.
#    database: '[ DATABASE_NAME ]'
#
# NODE COLLECTION: The name of the collection used for storing node definitions
#    nodecollection: '[ COLLECTIONS_NAME ]'
#
# FACT COLLECTION: The name of the collection used for storing facter facts
#    factcollection: '[ COLLECTION_NAME ]'
#
#
# [ JSON & YAML ]:
# DATA PATH: The path to which yaml or json files will be written. This is not needed for database_type: 'mongo'
#    data_path: '[ PATH ]'
#
#
# [ PUPPET INVENTORY SERVICE ]
# The Puppet Inventory Service must be setup on the puppet master in order to use fact interpolation with automaton.
#
# ENABLE FACTS: true or false. Set to true if you have the inventory service setup on your puppet master, and you
# want to use fact interpolation in node definitions.
#    enablefacts: '[ true | false ]'
#
# INVENTORY URL: The URL of your Inventory Service. This is default to your puppetmaster
#    inventoryurl:   '[ http://puppet | URL_TO_SERVICE ]'
#
# INVENTORY PORT: The port that your Inventory Service is listening.
#    inventoryport:  '[ 8140 | PORT ]'
#
# ENVIRONMENT: The environment from which to search in the Inventory Service.
#    environment:    '[ production | ENVIRONMENT ]'
#
#
# [ LOGGING CONFIGURATION ]
# ENABLE LOG: true or false to enable logging
#    enablelog: '[ true | false ]'
#
# LOG PATH: The path automaton will write log files.
#    logpath: '[ PATH ]'
#
# VERBOSE: true or false to enable verbose logging
#    verbose: '[ true | false ]'
#
# DEBUG: true or false to enable debug logging
#    debug: '[ true | false ]'
#
#

# [ Automaton Database Type ]
database_type:  'mongo'

# [ Mongo Configuration ]
mdb_hosts:      '10.40.30.60:9969,mongohost001b:27017,mongohost001c:27017'
replicaset:     'no'
#username:       ''
#password:       ''
database:       'automaton'
nodecollection: 'enc'
factcollection: 'facts'

# [ JSON & YAML ]
data_path:      '/home/shellfu/opt/nodes'

# [ PUPPET INVENTORY SERVICE ]
enablefacts:    'true'
inventoryurl:   'https://10.40.30.163'
inventoryport:  '8140'
environment:    'production'

# [ Logging Configuration ]
logpath:        '/home/shellfu/var/logs/automaton.log'
enablelog:      'true'
verbose:        'false'
debug:          'false'

